In [10]:
import numpy as np

In [ ]:
list = [1,2,3]

In [4]:
type(list)

list

In [7]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(list)

array([1, 2, 3])

In [14]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Build-in Methods

In [18]:
np.arange(0,5,2)

array([0, 2, 4])

In [20]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.zeros(2)

array([0., 0.])

In [24]:
np.ones(2)

array([1., 1.])

In [26]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [28]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [31]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [33]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
np.random.rand(4)

array([0.1527515 , 0.41621855, 0.85964657, 0.31003694])

In [38]:
np.random.randn(4,4)

array([[-2.16453296,  0.82947584,  0.12983954,  0.02839887],
       [-0.66437774,  0.44278618,  2.02170765,  0.88272644],
       [-0.13484813,  0.10343101,  0.32471604, -0.34409186],
       [ 0.74529544,  1.24631635,  1.62756326,  1.15324956]])

In [40]:
np.random.randint(10,20)

14

In [44]:
np.random.randint(10,20,5)

array([18, 15, 11, 19, 14])

In [45]:
arr1 = np.arange(10)
arr2 = np.random.randint(0,10,5)

In [46]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr2

array([6, 7, 8, 1, 2])

### Max()-Returns max-element,Same for Min()

In [48]:
arr1.max()

9

### Argmax()-Returns index value of max-element,Same for Argmin()

In [49]:
arr1.argmax()

9